"""empty message

Revision ID: 95e857e1cd9d
Revises: 
Create Date: 2022-05-01 10:47:31.664219

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95e857e1cd9d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('team',
    sa.Column('team_id', sa.String(length=10), nullable=False),
    sa.Column('team_name', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('team_id')
    )
    op.create_table('player',
    sa.Column('player_id', sa.String(length=50), nullable=False),
    sa.Column('player_name', sa.String(length=20), nullable=False),
    sa.Column('position', sa.String(length=10), nullable=True),
    sa.Column('back_number', sa.String(length=4), nullable=True),
    sa.Column('hitting_hand', sa.String(length=4), nullable=True),
    sa.Column('pitching_hand', sa.String(length=4), nullable=True),
    sa.Column('fk_team_id', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['fk_team_id'], ['team.team_id'], ),
    sa.PrimaryKeyConstraint('player_id')
    )
    op.create_table('hitter_score',
    sa.Column('score_id', sa.String(length=50), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('date_int', sa.Integer(), nullable=False),
    sa.Column('game_count', sa.Integer(), nullable=True),
    sa.Column('plate_appearance', sa.Integer(), nullable=True),
    sa.Column('time_at_bat', sa.Integer(), nullable=True),
    sa.Column('hit', sa.Integer(), nullable=True),
    sa.Column('double', sa.Integer(), nullable=True),
    sa.Column('triple', sa.Integer(), nullable=True),
    sa.Column('homerun', sa.Integer(), nullable=True),
    sa.Column('runs_batted_in', sa.Integer(), nullable=True),
    sa.Column('runs', sa.Integer(), nullable=True),
    sa.Column('stolen_base', sa.Integer(), nullable=True),
    sa.Column('base_on_ball', sa.Integer(), nullable=True),
    sa.Column('strikeouot', sa.Integer(), nullable=True),
    sa.Column('batting_average', sa.Float(), nullable=True),
    sa.Column('on_base_percent', sa.Float(), nullable=True),
    sa.Column('sluggin_percentage', sa.Float(), nullable=True),
    sa.Column('ops', sa.Float(), nullable=True),
    sa.Column('fk_player_id', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['fk_player_id'], ['player.player_id'], ),
    sa.PrimaryKeyConstraint('score_id')
    )
    op.create_table('pitcher_score',
    sa.Column('score_id', sa.String(length=50), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('date_int', sa.Integer(), nullable=False),
    sa.Column('game_count', sa.Integer(), nullable=True),
    sa.Column('win', sa.Integer(), nullable=True),
    sa.Column('loss', sa.Integer(), nullable=True),
    sa.Column('save', sa.Integer(), nullable=True),
    sa.Column('hold', sa.Integer(), nullable=True),
    sa.Column('innings_pitched_natural', sa.Integer(), nullable=True),
    sa.Column('innings_pitched_fraction', sa.String(length=10), nullable=True),
    sa.Column('number_of_pitches', sa.Integer(), nullable=True),
    sa.Column('hit', sa.Integer(), nullable=True),
    sa.Column('homerun', sa.Integer(), nullable=True),
    sa.Column('strike_out', sa.Integer(), nullable=True),
    sa.Column('base_on_balls', sa.Integer(), nullable=True),
    sa.Column('run', sa.Integer(), nullable=True),
    sa.Column('earned_run', sa.Integer(), nullable=True),
    sa.Column('era', sa.Float(), nullable=True),
    sa.Column('whip', sa.Float(), nullable=True),
    sa.Column('quality_start', sa.Integer(), nullable=True),
    sa.Column('fk_player_id', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['fk_player_id'], ['player.player_id'], ),
    sa.PrimaryKeyConstraint('score_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pitcher_score')
    op.drop_table('hitter_score')
    op.drop_table('player')
    op.drop_table('team')
    # ### end Alembic commands ###
